FROM node:lts-alpine

RUN apk add --no-cache libc6-compat
WORKDIR /usr/src/app
COPY ./package.json /usr/src/app
# COPY . /usr/src/app
RUN yarn install --frozen-lockfile

ENV APP_DEPLOY_TYPE "docker"
ENV API_USER_URL "http://user:9000"

EXPOSE 4200

CMD  yarn start web-ui
